services:
  php:
    build:
      context: .docker
      dockerfile: Dockerfile
      args:
        - USER_ID
        - GROUP_ID
    container_name: php-shortnr
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - XDEBUG_MODE=debug,coverage
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9000 start_with_request=yes
      - PHP_IDE_CONFIG=serverName=ddev
    expose:
      - "9000"
    stdin_open: true
    tty: true
