shortNr:
  types:
    page: "\\CPSIT\\Shortnr\\Service\\Processor\\PageProcessor"
    plugin: "\\CPSIT\\Shortnr\\Service\\Processor\\PluginProcessor" # add custom processor here

  _default:
    # support page id or hard-coded slug (detects it via is_numeric)
    notFound: "/fehler-404"
    # placeholder are based on the regex match groups {match-1}, {match-2}, {match-3}, ... etc
    regex: "/^([a-zA-Z]+?)(\\d+)[-]?(\\d+)?$/"
    regexGroupMapping: # regex group mapping
      prefix: "{match-1}"
      id: "{match-2}"
      languageId: "{match-3}"
    condition: # database conditions
      uid: "{match-2}"
      sysLanguageUid: "{match-3}"

  pages: # default page
    type: page
    prefix: PAGE
    table: pages
  press:
    prefix: pm
    type: plugin
    table: tx_bmubarticles_domain_model_article
    condition:
      articleType: press
    pluginConfig:
      extension: BmubArticles
      plugin: Articles
      pid: 289
      action: show
      controller: Article
      objectName: article # name for value for the UID
