services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CPSIT\Shortnr\:
    resource: '../Classes/*'
    exclude: '../Classes/Config/DTO'

  CPSIT\Shortnr\Service\PlatformAdapter\FileSystem\FileSystemInterface:
    alias: CPSIT\Shortnr\Service\PlatformAdapter\FileSystem\FileSystem
    public: true

  CPSIT\Shortnr\Service\PlatformAdapter\Typo3\PathResolverInterface:
    alias: CPSIT\Shortnr\Service\PlatformAdapter\Typo3\Typo3PathResolver
    public: true
