services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CPSIT\ShortNr\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Config/DTO'
      - '../Classes/Domain/DTO'
      - '../Classes/Service/Url/Condition/Operators/DTO'
      - '../Classes/Service/Url/Processor/DTO'
      - '../Classes/Service/PlatformAdapter/DTO'
      - '../Classes/Service/Url/Demand'
      - '../Classes/Service/Url/Regex/MatchResult.php'
      - '../Classes/Event'

  _instanceof:
    CPSIT\ShortNr\Service\Url\Condition\Operators\QueryOperatorInterface:
      tags: ['cps_shortnr.query.operators']
    CPSIT\ShortNr\Service\Url\Condition\Operators\ResultOperatorInterface:
      tags: ['cps_shortnr.result.operators']
    CPSIT\ShortNr\Service\Url\Processor\ProcessorInterface:
      tags: [ 'cps_shortnr.processors' ]

  CPSIT\ShortNr\Service\Url\Condition\ConditionService:
    arguments:
      $queryOperators: !tagged 'cps_shortnr.query.operators'
      $resultOperators: !tagged 'cps_shortnr.result.operators'

  CPSIT\ShortNr\Service\AbstractUrlService:
    arguments:
      $processors: !tagged 'cps_shortnr.processors'

  # Concrete services inherit
  CPSIT\ShortNr\Service\DecoderService:
    parent: CPSIT\ShortNr\Service\AbstractUrlService
  CPSIT\ShortNr\Service\EncoderService:
    parent: CPSIT\ShortNr\Service\AbstractUrlService

# Interface announcement
  CPSIT\ShortNr\Service\PlatformAdapter\FileSystem\FileSystemInterface:
    alias: CPSIT\ShortNr\Service\PlatformAdapter\FileSystem\FileSystem
    public: true
  CPSIT\ShortNr\Service\PlatformAdapter\Typo3\PathResolverInterface:
    alias: CPSIT\ShortNr\Service\PlatformAdapter\Typo3\Typo3PathResolver
    public: true
  CPSIT\ShortNr\Service\PlatformAdapter\Typo3\SiteResolverInterface:
    alias: CPSIT\ShortNr\Service\PlatformAdapter\Typo3\SiteResolver
    public: true
  CPSIT\ShortNr\Service\PlatformAdapter\Typo3\PageTreeResolverInterface:
    alias: CPSIT\ShortNr\Service\PlatformAdapter\Typo3\Typo3PageTreeResolver
    public: true

# event listener
  CPSIT\ShortNr\EventListener\CacheEventListener:
    tags:
      - name: event.listener
        method: handleEvents
        identifier: 'iki-sitepackage/news-event-listener'
        event:
          - TYPO3\CMS\Core\Cache\Event\CacheFlushEvent
# Config Resolver listener
  CPSIT\ShortNr\EventListener\DecodeConfigResolverListener:
    tags:
      - name: event.listener
        method: handleEvents
        identifier: 'shortNrConfigDecodeResolver'
        event:
          - CPSIT\ShortNr\Event\ShortNrDecodeConfigResolverEvent
  CPSIT\ShortNr\EventListener\EncodeConfigResolverListener:
    tags:
      - name: event.listener
        method: handleEvents
        identifier: 'shortNrConfigEncodeResolve'
        event:
          - CPSIT\ShortNr\Event\ShortNrEncodeConfigResolverEvent
  CPSIT\ShortNr\EventListener\DecodeVerifyListenerListener:
    tags:
      - name: event.listener
        method: handleEvents
        identifier: 'shortNrVerifyRequest'
        event:
          - CPSIT\ShortNr\Event\ShortNrVerifyRequestEvent
