services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CPSIT\ShortNr\:
    resource: '../Classes/*'

  CPSIT\ShortNr\Service\FileSystem\FileSystemInterface:
    alias: CPSIT\ShortNr\Service\FileSystem\FileSystem
    public: true
